name: Check linting, unit tests, and build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: clean install dependencies and build
      run: | 
        npm ci
        npm run grunt
